# Generated by Django 5.1.7 on 2025-03-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва новини')),
                ('description', models.TextField(verbose_name='Опис новини')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Слаг новини')),
                ('title', models.TextField(verbose_name='Особливості новини')),
                ('main_image', models.ImageField(upload_to='news/', verbose_name='Головне зображення новини')),
                ('news_image1', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Зображення перше новини')),
                ('news_image2', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Зображення друге новини')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення новини')),
                ('author', models.CharField(max_length=100, verbose_name='Автор статті новини')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва проєкту')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Слаг проєкту')),
                ('description', models.TextField(verbose_name='Опис проєкту')),
                ('title', models.TextField(verbose_name='Особливості проєкту')),
                ('main_image', models.ImageField(upload_to='projects/', verbose_name='Головне зображення проєкту')),
                ('project_image1', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Зображення перше проєкту')),
                ('project_image2', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Зображення друге проєкту')),
                ('status', models.CharField(choices=[('open', 'Відкритий'), ('closed', 'Закритий')], default='open', max_length=7, verbose_name='Статус проєкта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення проєкту')),
                ('author', models.CharField(max_length=100, verbose_name='Автор статті проєкту')),
            ],
        ),
    ]
