# Generated by Django 5.1.7 on 2025-04-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hands', '0002_alter_news_created_at_alter_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор статті новини'),
        ),
        migrations.AddField(
            model_name='news',
            name='author_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор статті новини'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Опис новини'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис новини'),
        ),
        migrations.AddField(
            model_name='news',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва новини'),
        ),
        migrations.AddField(
            model_name='news',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва новини'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.TextField(null=True, verbose_name='Особливості новини'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uk',
            field=models.TextField(null=True, verbose_name='Особливості новини'),
        ),
        migrations.AddField(
            model_name='project',
            name='author_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор статті проєкту'),
        ),
        migrations.AddField(
            model_name='project',
            name='author_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор статті проєкту'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Опис проєкту'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис проєкту'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва проєкту'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва проєкту'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.TextField(null=True, verbose_name='Особливості проєкту'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_uk',
            field=models.TextField(null=True, verbose_name='Особливості проєкту'),
        ),
    ]
