# Generated by Django 5.1.7 on 2025-04-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hands', '0003_news_author_en_news_author_uk_news_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='partner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='project',
            name='partner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Партнер'),
        ),
    ]
