# Generated by Django 5.1.7 on 2025-04-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hands', '0004_news_partner_project_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='partner_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='news',
            name='partner_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='project',
            name='partner_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='project',
            name='partner_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Партнер'),
        ),
    ]
